apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
spec:
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: gaarge/register:1.4
        ports:
        - containerPort: 8081
apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  selector:
    app: register-service
  ports:
  - port: 8081
    targetPort: 8081
